title = "Shaman Config"


[paths]
base = "D:/Coding/Shaman/Base"    # Folder for runtime program files.
downloads = "/downloads"                    # Where runtime downloads are stored and accessed
logs = "/logs"                              # Where log files are stored
data = "/data"                              # Where program data is stored

[authentication]
tmaUser = "dkowalczyk@icomm.co"                   # TMA Username
tmaPass = "k5170800"                            # TMA Password
cimplUser = "dan.kowalczyk@uplandsoftware.com"   # Cimpl Username
cimplPass = "Make!tCimpl"                       # Cimpl Password
verizonUser = "syscovzw2"                       # Verizon MyBiz Username
verizonPass = "Sysco2022!"                      # Verizon MyBiz Password

[logging]
level = "DEBUG"     # Valid levels are: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", with DEBUG showing the most info
maxSize = 10240     # Maximum log file size in kilobytes
backupCount = 10    # Number of old log files to keep

[database]
name = "Shaman.db"  # Default database name










