title = "Shaman Config"


[paths]
base = "D:/Coding/Shaman/Base"    # Folder for runtime program files.
downloads = "/downloads"                    # Where runtime downloads are stored and accessed
logs = "/logs"                              # Where log files are stored
data = "/data"                              # Where program data is stored

[authentication]
tmaUser = "dkowalczyk@icomm.co"                   # TMA Username
tmaPass = "k5170800"                            # TMA Password
cimplUser = "dkowalczyk@uplandsoftware.com"   # Cimpl Username
cimplPass = "Make!tCimpl"                       # Cimpl Password
verizonUser = "SYSCOVECFV"                       # Verizon MyBiz Username
verizonPass = "Tibbleton10!"                      # Verizon MyBiz Password
bakaUser = "WirelessMac"                        # Baka Ordering Username
bakaPass = "SyscoOrders2021"                    # Baka Ordering Password

[logging]
level = "DEBUG"     # Valid levels are: "DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL", with DEBUG showing the most info
maxSize = 10240     # Maximum log file size in kilobytes
backupCount = 10    # Number of old log files to keep

[cimpl]
skipVehicleCharger = true                       # If True, vehicle charger requests will be skipped entirely.
verizonSmartphoneBaseAccessory = "VerizonWallAdapter" # If this accessory is set to a valid accessoryID, it will be purchased in EVERY Verizon order.

[database]
name = "Shaman.db"  # Default database name










